### PR TITLE
Update to allow all versions of Angular 13

### PR DESCRIPTION
**Pull request by johannes-maxava**
Hi I have updated the `package.json` so all versions of angular 13 is supported. 

Can this please be tagged with version `4.3.1`

### CODE REVIEW

**Comment by johannes-maxava** [comment]
@antoantonyk can you please look at this PR, we are not able to use this module unless upgrade to at least the minor version specified in the package.json this actually means the module only supports a small subset to angular 13 versions.

**Comment by antoantonyk** [comment]
@johannes-maxava sure. let me take a look

**Comment by antoantonyk** [comment]
@johannes-maxava  sorry for the late reply. I have published the version new version [v4.3.1](https://github.com/antoantonyk/password-strength-meter/releases/tag/v4.3.1).

**Comment by antoantonyk** [comment]
Feel free to reopen this discussion if issue is still there

**Pull request closed without merging**
