### PR TITLE
feat: Angular 11 support

### PR DESCRIPTION
**Pull request by AngelCareaga**

### CODE REVIEW

**Comment by erikramalho** [comment]
Please Merge it!

**Comment by fabricioferreira** [comment]
Any plans to have this merged?

**Comment by antoantonyk** [comment]
@fabricioferreira  yeah.. actually. Some other changes are also in progress, will try to release this in coming weekend

**Comment by antoantonyk** [comment]
@AngelCareaga  Thank you for your contribution. Please check the latest changes and if this PR still helps, please reopen it.

**Pull request closed without merging**
